### ISSUE TITLE
Swag card items doesn't have same height; inconcistent height 

### ISSUE THREAD

**Issue by Muhammad0320** [swapagarwal/swag-for-dev#1097]
## Issue regarding the website

- [ ] I've checked that this isn't a duplicate issue.

When I checked the website , the cards height inconsistency was the first that caught my attention.

I would be happy if I'm assigned to do the tasd

**Comment by aslafy-z** [comment]
Sure, please give a go!

**Comment by Muhammad0320** [comment]
Okay thank you

**Comment by EliasLeguizamon123** [comment]
Hi, im new here.

Its this still open ? can i check this one ?

**Comment by aslafy-z** [comment]
Sure! I assigned you.

**Comment by EliasLeguizamon123** [comment]
Thank you, @aslafy-z. Could I ask you how to solve this problem?

I'm following the instructions to contribute, and I don't have any issues until I run the `npm start` command. The output of that command is as follows:


```
Failed downloading https://sendgrid.com/wp-content/uploads/2018/09/9-18_Hacktoberfest_Shirt_Front-960x960.jpg [1.4s]: Response code 404 (Not Found)
Downloaded https://s3.amazonaws.com/com.twilio.prod.twilio-docs/images/sticker-teaser-questionmark.width-1000.jpg [947.21ms]
Downloaded https://i.imgur.com/o7utTj2.png [1.2s]
Downloaded https://res.cloudinary.com/dsg3ucw55/image/upload/v1599671200/Logo_nstaby.svg [683.39ms]
Downloaded https://i.imgur.com/pU8KfaE.png [2.0s]
Downloaded https://i.imgur.com/tCJJKMe.png [488.90ms]
Downloaded https://i.imgur.com/HOoCHc7.jpg [680.87ms]
Downloaded https://i.imgur.com/2ciFNd8.png [542.86ms]
Downloaded http://devblogs.microsoft.com/xamarin/wp-content/uploads/sites/44/2019/10/medium_25686-c9dd82896c9e66bb82600f256444abe6.png [504.65ms]
Downloaded https://i.imgur.com/CpZBbcB.png [498.73ms]
Downloaded https://i.imgur.com/ZyhS12p.png [835.89ms]
Downloaded https://s3.amazonaws.com/uno-website-assets/wp-content/uploads/2019/08/21141002/diagram-991x1024.png [1.5s]
Downloaded https://i.imgur.com/JXYEkT4.png [1.4s]
Downloaded swag-images with 1 error
[17:23:10] 'swag-img:download' errored after 7.1 s
[17:23:10] Error: Failed to download images
    at /home/swag-for-dev/gulpfile.js:126:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:23:10] 'swag-img' errored after 7.12 s
[17:23:10] 'build' errored after 7.13 s
[17:23:10] 'default' errored after 7.14 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swag-for-dev@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swag-for-dev@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2024-01-19T20_23_10_454Z-debug.log
```


nvm version: `0.39.1`
nodejs version: `v12.19.0`
system: Ubuntu `22.04.3 LTS x86_64`

**Comment by aslafy-z** [comment]
@EliasLeguizamon123 I fixed the issue with https://github.com/swapagarwal/swag-for-dev/pull/1253
Please have a new try :)

**Comment by EliasLeguizamon123** [comment]
Ok, thanks for your help, I'm check now

**Comment by EliasLeguizamon123** [comment]
@aslafy-z fixed with [#1254](https://github.com/swapagarwal/swag-for-dev/pull/1254)

**Comment by karthickbharathwaj97** [comment]
@aslafy-z  is this issue still  there? could i check this out?
<img width="938" alt="image" src="https://github.com/user-attachments/assets/a6a21b3d-9401-4440-b9d2-34931f920fff">
